apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kubelet-throttler
spec:
  selector:
    matchLabels:
      name: kubelet-throttler
  template:
    metadata:
      labels:
        name: kubelet-throttler
      annotations:
        woehrl.net/skip-throttle: "true"
    spec:
      serviceAccountName: kubelet-throttler
      hostNetwork: true
      initContainers:
        - name: init-cni
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command:
            - "./cni-init"
          args:
            - "--cni-bin-dir=/opt/cni/bin"
            - "--cni-config-dir=/etc/cni/net.d"
            - "--daemon-port={{ .Values.hostPort }}"
            - "--max-wait-time-in-seconds={{ .Values.maxWaitTimeInSeconds }}"
          volumeMounts:
            - name: cni-bin-dir
              mountPath: /opt/cni/bin
            - name: cni-config-dir
              mountPath: /etc/cni/net.d
      containers:
        - name: node-daemon
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command:
            - "./node-daemon"
          args:
            - "--throttler-limit={{ .Values.throttlerLimit }}"
            - "--taint-to-remove={{ .Values.taintToRemove }}"
            - "--daemon-port={{ .Values.hostPort }}"
            - "--debug-logging={{ .Values.debugLogging }}"
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - containerPort: {{ .Values.hostPort }}
              protocol: TCP
          livenessProbe:
            grpc:
              port: {{ .Values.hostPort }}
            initialDelaySeconds: 10
      tolerations:
        - key: {{ .Values.taintToRemove }}
          effect: NoSchedule
        {{- with .Values.tolerations }}
        {{ toYaml . | nindent 8 }}
        {{ end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      {{- with .Values.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      volumes:
        - name: cni-bin-dir
          hostPath:
            path: /opt/cni/bin
            type: DirectoryOrCreate
        - name: cni-config-dir
          hostPath:
            path: /etc/cni/net.d
            type: DirectoryOrCreate
