apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kubelet-throttler
spec:
  selector:
    matchLabels:
      name: kubelet-throttler
  template:
    metadata:
      labels:
        name: kubelet-throttler
    spec:
      serviceAccountName: kubelet-throttler
      initContainers:
        - name: init-cni
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command:
            - "./cni-init"
          args:
            - "--cni-bin-dir=/opt/cni/bin"
            - "--cni-config-dir=/etc/cni/net.d"
            - "--daemon-port={{ .Values.hostPort }}"
            - "--max-wait-time-in-seconds=10"
          volumeMounts:
            - name: cni-bin-dir
              mountPath: /opt/cni/bin
            - name: cni-config-dir
              mountPath: /etc/cni/net.d
      containers:
        - name: node-daemon
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command:
            - "./node-daemon"
          args:
            - "--throttler-limit={{ .Values.throttlerLimit }}"
            - "--taint-to-remove={{ .Values.taintToRemove }}"
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - containerPort: 50051
              hostPort: {{ .Values.hostPort }}
              protocol: TCP
          livenessProbe:
            grpc:
              port: 50051
            initialDelaySeconds: 10
      tolerations:
        - key: {{ .Values.taintToRemove }}
          effect: NoSchedule
      volumes:
        - name: cni-bin-dir
          hostPath:
            path: /opt/cni/bin
            type: DirectoryOrCreate
        - name: cni-config-dir
          hostPath:
            path: /etc/cni/net.d
            type: DirectoryOrCreate
