{{ if .Values.defaultThrottleConfig.enabled }}
apiVersion: woehrl.net/v1alpha
kind: PacemakerConfig
metadata:
  name: default-pacemaker-config
spec:
  priority: 0
  nodeSelector: {}
  throttleConfig: {{ .Values.defaultThrottleConfig.config | toYaml | nindent 4 }}
{{ end }}
