# github action which runs a make script to setup go

name: Go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Git Version
        id: version
        uses: paulhatch/semantic-version@v5.3.0
        with:
          tag_prefix: "v"
          version_format: "${major}.${minor}.${patch}"
      - name: Setup buildx
        uses: docker/setup-buildx-action@v3
      - name: Run make
        run: |
          VERSION=${{ steps.version.outputs.version }} make docker-build
